### PR TITLE
Converted list of parameters to single instance, fixes #3

### LINKED ISSUE #3: RFC-6838: parameter should not be specified more than once
According to [Parameter Requirements](https://tools.ietf.org/html/rfc6838#page-13):
> It is an error for a specific parameter to be specified more than once.

So lets change `params()` signature of `MimeType` from `Map<String, List<String>>` to 
`Map<String, String>`. If parameter specified more than once `params()` should throw an exception.

### PR DESCRIPTION
**Pull request by Viciouss**
I converted the code so that a parameter can only exist once, otherwise an IllegalStateException is thrown. To be sure that it works, I created a negative test which triggers the exception and I extended the charset test to also include a negative test which triggers the IOException.

Compilation and unit tests were ok, Checkstyle bothered me with the line endings which should be corrected on commit - I'm using Windows :flushed:

### CODE REVIEW

**Comment by Viciouss** [comment]
Not sure why, but my local results of Checkstyle were different from what I got here, not counting the line endings. I'm curious why this happened but too tired to find out today.

File: src/main/java/com/g4s8/mime/MimeTypeOf.java [hunk 1]
```diff
@@ -84,20 +82,22 @@ public String subtype() throws IOException {
...
         for (int id = match.end(); id < this.src.length(); id = param.end()) {
             param.region(id, this.src.length());
             if (!param.lookingAt()) {
                 throw new IOException("Invalid mime-type params format");
             }
             final String name = param.group(1);
-            if (!map.containsKey(name)) {
-                map.put(name, new LinkedList<String>());
+            if (map.containsKey(name)) {
+                throw new IllegalStateException(
```
Comment (g4s8) [inline src/main/java/com/g4s8/mime/MimeTypeOf.java]: Here should be checked exception, declared in method signature. You can use `IOException` here or one of successor that suite for error type. If you don't like any you can make new exception class extended from `IOException`. 
BTW if you don't have enough time you can put `@todo` directive ([how to format](https://github.com/yegor256/pdd#how-to-format)) in class javadoc wich will automatically create new github issue.

**Review by g4s8 — CHANGES_REQUESTED** [review]
@Viciouss code looks good, but see my comments.
 
You may have different line-endings checkstyle behavior because `git commit` can automatically convert line-endings. Try to set line-endings to unix ('\n') format in your IDE.

File: src/main/java/com/g4s8/mime/MimeTypeOf.java (hunk 1 above)
Comment (Viciouss) [reply src/main/java/com/g4s8/mime/MimeTypeOf.java]: From the Javadoc of IOException I'd say that it's okay for this case. I had a look at the class hierarchy of IOException but couldn't find anything better, so I'll go with it. A custom exception that extends IOException wouldn't have any additional benefits.

**Review by g4s8 — APPROVED** [review]

**Comment by g4s8** [comment]
@rultor merge
